### ISSUE TITLE
CommandNotFoundException for contao:migrate command

### ISSUE THREAD

**Issue by qzminski** [terminal42/deployer-recipes#11]
Hey @richardhj in the PR https://github.com/terminal42/deployer-recipes/pull/10 you introduced the `contao:migrate` command. However this throws a `CommandNotFoundException` exception in e.g. Contao 4.4. Although the deployment runs smoothly, my Sentry is catching all those exceptions.

Is there any way we can prevent it and check if the command exists before running it?

**Comment by richardhj** [comment]
If there is an exception, we can catch it. Maybe we should broaden the try-catch-clause to catch any \Exception?

**Comment by qzminski** [comment]
I don't think that would work because the exception is thrown on the app level and not on the deployer level. The deployer runs a shell command and thus instantiates a separate PHP process to execute that command.

**Comment by richardhj** [comment]
Ah, understood.
We can run `php vendor/bin/contao-console list | grep contao:migrate` and check if there is console output.
On the other hand, silencing the `CommandNotFoundException` in the Sentry configuration would be totally fine IMHO as well.

**Comment by qzminski** [comment]
> We can run php vendor/bin/contao-console list | grep contao:migrate and check if there is console output.

That sounds like a plan 👍can you check if that works out?

> On the other hand, silencing the CommandNotFoundException in the Sentry configuration would be totally fine IMHO as well.

Oh absolutely not, that is a totally valid exception that should be reviewed 😉

**Comment by richardhj** [comment]
Changed in 4b6359aa5c601c4ee7ff6b14f7dae8eab5b68544. This will only work once 4.9.0 is released, but that's okay for me since I updated my projects to use the `contao:migrate` task in the deploy.php already.
