### ISSUE TITLE
Automatically detect the location of parameters.yml file 

### ISSUE THREAD

**Issue by richardhj** [terminal42/deployer-recipes#5]
bd804f87ce75ad9eb2b2c7bc349aec5157859c7d

This is actually without functionality atm because the `symfony` recipe already sets the `shared_files` variable in https://github.com/deployphp/deployer/blob/74b3f73e60acee2eccc0d53c270a7c4335d5b5a7/recipe/symfony.php#L24. 
I changed to the symfony4 recipe and it looks fine.

**Proposal:**
Change from symfony to symfony4 recipe in the bootstrap file.

In addition, we need to adjust the `deploy:platform_release` task to choose the correct parameters.yml file.

**Comment by qzminski** [comment]
Does it change anything if `symfony4` recipe also explicitly sets the shared files?

https://github.com/deployphp/deployer/blob/74b3f73e60acee2eccc0d53c270a7c4335d5b5a7/recipe/symfony4.php#L13

**Comment by richardhj** [comment]
Well, the symfony4 recipe is parsed before our symfony recipe (load order).
This means, `symfony4.php` _sets_ the `shared_files` (i.e. `.env`) and `symfony.php` _adds_ the `parameters.yml` correspondingly.

**Comment by richardhj** [comment]
This got fixed in 97f0dbfb423768d7069702b3afb3e6f23749d798 and c9530d48678b53af268ee5bab647aec886befd68.
