### ISSUE TITLE
.env file is not excluded

### ISSUE THREAD

**Issue by Toflar** [terminal42/deployer-recipes#9]
We only exclude `.env.local` in https://github.com/terminal42/deployer-recipes/blob/e74051048f35e2aa972d5e1215378ec6031c38cc/recipe/deploy.php#L20.

I know this is fine because `.env` is the one that should be comitted to the git repository. However, if you have no `.env` locally and only use `.env.local` this one is not considered. So you cannot have env variables locally with only a `.env.local` which means you need to have `.env`. But again, that's not what you want to deploy.

**Comment by richardhj** [comment]
Solution: only exclude .env when .env.local is present?

**Comment by Toflar** [comment]
Sounds legit to me :D I thought about it too much 🤦‍♂

**Comment by richardhj** [comment]
Ok, will update the script later ;-)

**Comment by aschempp** [comment]
🤔 but I might not have a `.env.local` locally but have one on the server?

**Comment by aschempp** [comment]
> However, if you have no .env locally and only use .env.local this one is not considered. So you cannot have env variables locally with only a .env.local which means you need to have .env.

This is also how the DotEnv component works. You can't have a `.env.local` without a `.env`

**Comment by Toflar** [comment]
Jup. Which is why I would like the change. If you develop locally you have to add `APP_ENV=dev` in your `.env` file because adding 2 files makes no sense and deploying it makes no sense either.

**Comment by qzminski** [comment]
So we can exclude `.env` completely because it is an environmental (i.e. individual per server) thing. Is that right?

**Comment by Toflar** [comment]
No, if you have a `.env` that is actually committed to the repository (with default values, e.g. `COOKIE_WHITELIST`) then you want to deploy that.

**Comment by qzminski** [comment]
Then I don't know what's the issue and how it can be solved 🤷🏻‍♂️

**Comment by richardhj** [comment]
> 🤔 but I might not have a `.env.local` locally but have one on the server?

is that ever the case?

**Comment by Toflar** [comment]
Yes it is. Okay let me describe you again.
Facts: If you have no `.env`, the `.env.local` is never loaded.

### Situation 1, I need a `.env` with default settings being deployed to all my systems

E.g. because I want to deploy `COOKIE_WHITELIST=foobar` to all systems.
Locally I would then have

* `.env` with `COOKIE_WHITELIST=foobar`
* `.env.local` with `APP_ENV=dev` because I want to work in dev mode

So when I deploy, `.env.local` needs to be excluded. `.env` should not be excluded.

### Situation 2, I don't a `.env` with default settings being deployed to all my systems

Locally I would then have

* `.env` with `APP_ENV=dev` because I want to work in dev mode

It's super cumbersome to have `.env` with `APP_ENV=prod` and `.env.local` with `APP_ENV=dev` only to work in dev mode locally. It's not very convenient. And having only `.env.local` doesn't work as we know.

So when I deploy, `.env` must absolutely not be deployed because it's my dev settings and the deployed app would suddenly run in dev mode.

**Comment by qzminski** [comment]
So just add `add('exclude', ['.env']);` whenever you need to. I don't think you can automate this process. Also, it looks very appropriate (at least by design) to have two files in 2nd situation. It may not be super convenient but still that's how DotEnv component works and that's how it should be done.

**Comment by Toflar** [comment]
Nope, I want automatism here for sure :)

**Comment by aschempp** [comment]
I don't see why we should solve that. If you need to configure something for only local, then use `.env.local`. That means you have to add an empty `.env` file, which is totally ok to me. You can commit that empty file if you want to. Don't do *if-else* on which file to use, always use the same file for the same thing.

**Comment by Toflar** [comment]
I need `APP_ENV=dev` locally for all of my projects. So I should commit an empty `.env` file for all them? That seems a bit nonsense to me.

**Comment by aschempp** [comment]
no, if you need that locally for all your projects, set it up as an actual env variable in your server/host 😆

**Comment by Toflar** [comment]
Not an option either. I'll just implement it myself, no problem.
